objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Income__c</fullName>
        <label>Annual Income</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <label>Bank</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IncomeType__c</fullName>
        <label>IncomeType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Paycheck__c</fullName>
        <label>Paycheck</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Loan_Application__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Applications</relationshipLabel>
        <relationshipName>Loan_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employer_Name__c</fullName>
        <label>Employer Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Duration__c</fullName>
        <label>Loan Duration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan_Type__c</fullName>
        <label>Loan Type</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Applied</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/registerLoanApplicant.cls
public
without sharing class registerLoanApplicant {

  /********************************************************************************************************
   *  @author          Ravvinder Singh
   *  @description     to create Account,Contact and Opportunity
   *  @param
   *  @date            Sep 19, 2021
   *********************************************************************************************************/

  @AuraEnabled public static String createLoanApplicant(String loanData) {
    String referenceId = '';
    if (String.isNotBlank(loanData)) {
      // Update the order record
      jsonDeserialize jsonObject =
          (jsonDeserialize) JSON.deserializeStrict(loanData, jsonDeserialize.class);

      final Account acc = new Account();
      final Contact con = new Contact();
      final Loan_Application__c loanApplication = new Loan_Application__c();

      acc.Name = jsonObject.FirstName;
      insert acc;

      con.FirstName = jsonObject.FirstName;
      con.LastName = jsonObject.LastName;
      con.Email = jsonObject.Email;
      try {
        con.Phone = jsonObject.Phone;
        con.Bank__c = jsonObject.Bank;
        con.IncomeType__c = jsonObject.IncomeType;
        con.Paycheck__c = jsonObject.Paycheck;
        con.Annual_Income__c = jsonObject.Salary;
        con.AccountId = acc.Id;

        insert con;

        /*loanApplication.Name__c = jsonObject.FirstName + jsonObject.LastName;*/
        loanApplication.Status__c = 'Applied';
        loanApplication.Close_Date__c = Date.parse('12/12/2021');
        loanApplication.Employer_Name__c = jsonObject.company;
        loanApplication.Loan_Duration__c = Decimal.valueOf(jsonObject.Duration);
        loanApplication.Loan_Type__c = jsonObject.LoanType;
        loanApplication.Amount__c = Decimal.valueOf(jsonObject.LoanAmount);
        loanApplication.Account__c = acc.Id;

        insert loanApplication;

        referenceId = [SELECT Name FROM Loan_Application__c WHERE Id =:loanApplication.Id][0].Name;

      } catch (DmlException de) {
        throw new AuraHandledException(de.getDmlMessage(0));
      }
    }
    return referenceId;
  }

  /********************************************************************************************************
   *  @author          Ravvinder Singh
   *  @description     to fetch loan application
   *  @param
   *  @date            Sep 19, 2021
   *********************************************************************************************************/

  @AuraEnabled(cacheable = true) public static list<Loan_Application__c> getLoanApplication(
      String applicationNumber) {
    List<Loan_Application__c> loandetails = new List<Loan_Application__c>();
    try {

      loandetails = [select Name,
                      Status__c,
                      Loan_Type__c,
                      Amount__c from Loan_Application__c where Name =:applicationNumber];

      return loandetails;
    } catch (QueryException e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
  public
  class jsonDeserialize {
    public
    String FirstName;
    public
    String DOB;
    public
    String Gender;
    public
    String Email;
    public
    String LastName;
    public
    String Phone;
    public
    String Bank;
    public
    String IncomeType;
    public
    String Paycheck;
    public
    String Salary;
    public
    String company;
    public
    String Duration;
    public
    String LoanType;
    public
    String LoanAmount;
    public
    String PostalCode;
  }
}